### ISSUE TITLE
Feature Request: Android Whiteboard

### ISSUE THREAD

**Issue by cforce** [mconf/mconf-mobile#1]
I found this artcicle (http://mobile.dzone.com/news/free-android-app-source-code?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+javalobby%2Ffrontpage+%28Javalobby+%2F+Java+Zone%29) and thought that integrated into mconf could be a new module for adroid whiteboard support in BBB.

Just an idea and i wanted this piece of code to show to you.

**Comment by zhouYuFen** [comment]
You have to BBB - Android implements a whiteboard?

**Comment by fcecagno** [comment]
Hi @zhouYuFen,
This project was discontinued. We're developing a new mobile client using Adobe Air, which will have whiteboard soon. You can find the source code here: https://github.com/mconf/bbb-air-client
